from googletrans import Translator
import pydeepl

def translate(title:str):
    trans = Translator()
    return (trans.translate(title, dest='vi', src='en')).text

titles = ["hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my friend!",
          "hello my wife!",
          ]

for title in titles:
    print(translate(title))